version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
install:
- cmd: nuget restore IoTDeviceSDKWrapper.sln
build:
  verbosity: minimal
after_test:
- ps: .\PackAndPush.ps1
artifacts:
- path: '*.nupkg'
  name: NuGetPackage